# Generated by Django 5.0.6 on 2024-06-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('2', '2'), ('5', '5'), ('4', '4'), ('1', '1'), ('3', '3')], max_length=5)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Album', to='musician.musician')),
            ],
        ),
    ]
